### ISSUE TITLE
Link to K8s cheat sheet errors with 404 

### ISSUE THREAD

**Issue by moyni77** [LeCoupa/awesome-cheatsheets#157]
Access to k8s link via webpage errors with http 404 error. 
Please fix link,

**Comment by LeCoupa** [comment]
Hello, where is it? The link in the readme is working.

**Comment by moyni77** [comment]
From the website page if click on k8s, which is trying to do the below

https://github.com/LeCoupa/awesome-cheatsheets/blob/master/tools/kubernetes.sh 

Hope this helps.

**Comment by LeCoupa** [comment]
Alright I see

**Comment by barakadanny** [comment]
I can't access the link

**Comment by barakadanny** [comment]
or the problem is already resolved?

**Comment by moyni77** [comment]
No it's still not visible, I've just tried again. From main repo click https://lecoupa.github.io/awesome-cheatsheets/ then from the very bottom of the page, click on Kubernetes cheat sheet, you receive a 404 error, page missing. I think it's attempting to link to https://github.com/LeCoupa/awesome-cheatsheets/blob/master/tools/kubernetes.sh.

**Comment by connorteague** [comment]
I have created a PR to resolve this issue [here](https://github.com/LeCoupa/awesome-cheatsheets/pull/168)
